### ISSUE TITLE
emacs/evil package

### ISSUE THREAD

**Issue by wbolster** [insidewhy/colemak#1]
+1 to these configs, they make the most sense to me as well. i arrived at this layout independently, except for the brilliant touch to swap l/u (u/i on qwerty) which preserves muscle memory for insert/undo.

these configurations inspired me to create a similar config for emacs/evil (vim-like editing in emacs). i plan to publish it as an emacs package once i finish it.

this "issue" is merely a thank you note; feel free to close it right away. :)

**Comment by insidewhy** [comment]
Oh Netherlands please brexit me with you! You'll vouch for me right: "He wrote this really cool vim config". I used to use a vim mode type emacs thing back in the 90s called viper. Takes me back.

**Comment by wbolster** [comment]
heh. continent cut off. :)

imho, viper was not good enough for vim power users. it always felt quite not thorough enough.

evil-mode (more recent) is awesome. i was a heavy vim user, but now, a few months after my conversion (this is a religious thing after all), i can only conclude that this is way better than vim ever was for me, because the underlying emacs platform is simply superior. and with evil, emacs finally has a decent editor. i instantly felt at home.

```
— wouter
```

## 

sent from my phone. please forgive my tpyos.

**Comment by insidewhy** [comment]
Yeah viper was always a bit weak and laggy which is why I switched back. LISP plugins are what made me check it out and hang along for a bit. During my next break I will try evil-mode, does it support asynchronous or multi-threaded plugins?

**Comment by wbolster** [comment]
yes, flycheck is awesome. 

```
— wouter
```

## 

sent from my phone. please forgive my tpyos.

**Comment by insidewhy** [comment]
Fuck Brexit.

**Comment by wbolster** [comment]
i approve of this conversation

**Comment by wbolster** [comment]
here it is!

https://github.com/wbolster/evil-colemak-basics
