### ISSUE TITLE
t/f and end of word rotation

### ISSUE THREAD

**Issue by wbolster** [insidewhy/colemak#2]
hey, in case you're interested, to get slightly better ergonomics for "end of word" (qwerty `e` in vim) and "jump to char" (qwerty `f` in vim), the vim+colemak shuffle can be improved by putting both of these back into their qwerty position. this comes at the expense of putting "jump until char" (qwerty `t` in vim) at the hard to reach colemak `j` (qwerty `y`) position. details at https://github.com/wbolster/evil-colemak-basics/issues/2#issuecomment-259234998

**Comment by insidewhy** [comment]
:baby_symbol: :fog: :foggy: that could be good I'll probably try it, thanks.

**Comment by insidewhy** [comment]
I didn't like it so much.

**Comment by wbolster** [comment]
it's ok. you are allowed to make your own bad life choices.

**Comment by insidewhy** [comment]
hahaha, when I try to joke like that everyone thinks I'm being an asshole. Dry humour is good no? ;)

**Comment by wbolster** [comment]
yes, imho one is allowed to make sarcastic bad jokes without undoing them with emojis as long as one also makes similar self-condescending jokes about oneself. ;)
